modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Stalemated/quests_teams_fixes/issuess"
license = "MIT"

[[mods]]
modId = "quests_teams_fixes"
version = "${version}"
displayName = "Quests & Teams Fixes"
authors = "Stalemated"
description = '''
Completely disables FTB Teams, disbands any existing teams, and fixes some bugs from FTB Quests.
'''
logoFile = "META-INF/quests_teams_fixes_small.png"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/quests-teams-fixes"

[[dependencies.quests_teams_fixes]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quests_teams_fixes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quests_teams_fixes]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.quests_teams_fixes]]
modId = "ftbquests"
mandatory = true
versionRange = "[2001.4.18,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.quests_teams_fixes]]
modId = "ftbteams"
mandatory = true
versionRange = "[2001.3.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.quests_teams_fixes]]
modId = "ftblibrary"
mandatory = true
versionRange = "[2001.2.12,)"
ordering = "AFTER"
side = "BOTH"