# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.1.0
maven_group = com.stalemated.qtfixes
archives_name = quests_teams_fixes
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.20.1
yarn_mappings = 1.20.1+build.1

# Dependencies
architectury_api_version = 9.2.14
fabric_loader_version = 0.19.3
fabric_api_version = 0.92.11+1.20.1
forge_version = 1.20.1-47.4.22
ftb_library_id_fabric = 8226926
ftb_teams_id_fabric = 7499808
ftb_library_id_forge = 8226927
ftb_teams_id_forge = 7499810
ftb_quests_id_fabric = 7608803
ftb_quests_id_forge = 7608804
